-- postgres_migrate.version definition

-- Drop table

-- DROP TABLE postgres_migrate.version;

CREATE TABLE postgres_migrate.version (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный технический идентификатор
	created_at timestamptz NULL, -- Дата создания элемента
	modified_at timestamptz NULL, -- Дата последнего изменения элемента
	name Text,
	description Text,
	
	CONSTRAINT version_pkey PRIMARY KEY (id)
);
COMMENT ON COLUMN postgres_migrate.version.id IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN postgres_migrate.version.created_at IS 'Дата создания элемента';
COMMENT ON COLUMN postgres_migrate.version.modified_at IS 'Дата последнего изменения элемента';
